讲解词列表:
  火箭展厅: "在您右手边的是中国研制的“长征系列”运载火箭家族模型。 “长征一号” 是我国第一种运载火箭型号， 1970年4月24日成功地将 “东方红一号”卫星送入预定轨道，奠定了“长征”系列火箭发展的基础。"
  卫星展厅: "这是东方红一号卫星模型，1970年4月24日，东方红一号卫星搭载在长征一号运载火箭上从中国酒泉卫星发射中心成功发射。 两弹一星功勋科学家、我校校友孙家栋院士，参与了东方红一号卫星的研制和发射工作。发射手胡世祥中将同为我校校友。"
  航天器展厅: "人造地球卫星是环绕地球在空间轨道上运行的无人航天器，也是发射数量最多、用途最广、发展最快的航天器。自 1970年4月24日成功发射第一颗人造卫星起，我国已形成7个卫星系列。"
  运载火箭展厅: "这是我国发射的第一颗返回式卫星“尖兵一号”的模型及其返回舱实物。1975年在太原卫星发射中心用长征二号运载火箭发射升空。自此，中国成为世界上第3个掌握卫星返回技术的国家。"