robot_position:
  x: 0
  y: 0
  z: 0

exhibits:
  - id: 1
    name: "东方红一号"
    position:
      x: -1
      y: -1
      z: 3
  - id: 2
    name: "########################长征一号"
    position:
      x: -3
      y: 1
      z: 1
