museums:
  - name: 东方红一号展区
    exhibits: [东方红一号卫星]
  - name: 孙家栋院士成就展区
    exhibits: [孙家栋院士]
  - name: 中国航天工程成就展区
    exhibits: [长征一号火箭, 长征二号火箭, 长征五号火箭]
  - name: 中国人造地球卫星展区
    exhibits: [人造地球卫星]
  - name: 气象卫星风云四号展区
    exhibits: [风云四号气象卫星]
  - name: 北斗导航卫星展区
    exhibits: [北斗导航卫星]
  - name: 科学实验卫星墨子号展区
    exhibits: [墨子号科学实验卫星]
  - name: 气象卫星风云一号展区
    exhibits: [风云一号气象卫星]
  - name: 返回式卫星尖兵一号展区
    exhibits: [尖兵一号返回式卫星]
  - name: 电子侦察卫星长空一号展区
    exhibits: [长空一号卫星]
  - name: 中国探月工程展区
    exhibits: [嫦娥二号卫星, 嫦娥三号落月组合体, 嫦娥五号探测器]
  - name: 高分专项工程展区
    exhibits: [高分二号卫星]
  - name: 中国载人航天工程展区
    exhibits: [神舟一号飞船, 天宫一号, 天舟一号货运飞船, 天舟二号货运飞船, 天舟三号货运飞船]
  - name: 载人飞船神舟五号展区
    exhibits: [神舟五号载人飞船]
  - name: 航天员展区
    exhibits: [航天员]
  - name: 深空探测展区
    exhibits: [天问一号探测器]


task_categories:
  - 参观
  - 休眠
  - 问答
  - 继续
  - 无关

few_shots:
  Q-参观:
    - 带我参观中国探月工程展区吧
    - 我想看看东方红一号卫星
  A-参观:
    - 参观 孙家栋院士成就展区
    - 参观 中国人造地球卫星展区
  Q-参观-相对:
    - 继续参观下一个展厅吧
    - 我想看看之前的展厅
  A-参观-相对:
    - 参观 上一个
    - 参观 下一个
  Q-问答:
    - 我想了解一下嫦娥二号卫星
  A-问答:
    - 问答
  Q-问答-指向:
    - 介绍一下这个展品
  A-问答-指向:
    - 问答 指着
  Q-休眠:
    - 不要再继续讲解了
    - 可以了，停下吧
    - 原地休眠
  A-休眠:
    - 休眠
  Q-继续:
    - 没有了
    - 我没有问题了
    - 继续参观吧
  A-继续:
    - 继续

# 引用该配置文件的位置
# catkin_dt/src/voice_pkg/scripts/interrupt/LLM/apply.py      50, 90