museums:
  - name: 火箭展厅
    exhibits: [长征一号, 神州十五号]
  - name: 卫星展厅
    exhibits: [东方红卫星, 紫丁香一号卫星]
  - name: 航天器展厅
    exhibits: [天宫一号, 嫦娥四号]
  - name: 运载火箭展厅
    exhibits: [长征七号, 长征十一号]

task_categories:
  - 参观
  - 休眠
  - 问答
  - 继续
  - 无关

few_shots:
  参观:
    - 带我参观火箭展厅吧
    - 我想看看紫丁香卫星
  参观-相对:
    - 继续参观下一个展厅吧
    - 我想看看之前的展厅
  问答:
    - 我想了解一下北斗卫星
  问答-指向:
    - 介绍一下这个展品
  休眠:
    - 不要再继续讲解了
    - 可以了，停下吧
    - 原地休眠
  继续:
    - 没有了
    - 我没有问题了
    - 继续参观吧

openai_api_key:
  - "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"

# 引用该配置文件的位置
# catkin_dt/src/voice_pkg/scripts/interrupt/LLM/testgpt4.py   18
# catkin_dt/src/voice_pkg/scripts/interrupt/LLM/apply.py      50, 90
# catkin_dt/src/voice_pkg/scripts/interrupt/LLM/testLLM.py    83