museums:
  - name: 卫星展厅
    exhibits: [东方红卫星, 紫丁香一号卫星]
  - name: 火箭展厅
    exhibits: [火箭一号, 神州十五号]

task_categories:
  - 参观
  - 休眠
  - 问答
  - 继续
  - 无关

few_shots:
  参观:
    - 带我看看火箭展厅吧
    - 我想看看紫丁香卫星
  问答:
    - 我想了解一下北斗卫星
  休眠:
    - 我不想听了
    - 可以了停下吧
  继续:
    - 没有了
    - 我没有问题了
    - 继续参观吧

openai_api_key:
  - "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"